frequency_mhz: 433.0
cs_pin: CE1
reset_pin: D25
packets_per_transmit: 1
transmit_per_second: 0.5
callsign: CLSIGN
data_types:
  - send_time: Q
  - ping_time: Q
  - bandwidth: i
  - spreading: h
  - tx_power: h
  - test_num: H
  - orig_rssi: d
  - orig_snr: d
