packets_per_transmit: 1
transmit_per_second: 5
callsign: CLSIGN
data_order:
  - timestamp
  - bandwidth
  - spreading
  - tx_power
  - packet_num
data_types:
    timestamp: d
    bandwidth: i
    spreading: i
    tx_power: H
    packet_num: H
