### Radio configuration file template for FSK transmissions. ###

# Core Radio Parameters
frequency:    0.0       # Center frequency in MHz
fdev:         0.0       # Frequency deviation in kHz
bitrate:      0.0       # Bitrate in kbps
tx_power:     0         # Transmit power in dBm

# Other Radio Parameters
amp_mode:     D         # D=disabled, B=bypass, T=transmit, R=receive
timeout:      0.0       # Receive timeout in seconds
packet_delay: 0.0       # Transmit interval in seconds

# Addresses
self_address: 0         # Current device's node address (0-255, 255=receive all)
dest_address: 0         # Destination device's node address (0-255, 255=send to all)
accept_broad: false     # Whether we accept broadcast packets (packets sent to all)

# Logging
verbose:      true      # Whether we print verbose output to the terminal
log_name:     log       # Log file naming pattern (null = no logging)
log_dir:      logs      # Directory to store logs (null = current dir)

# Raspberry Pi Pin Usage
pins:
  transceiver:
    sck:      SCK
    mosi:     MOSI
    miso:     MISO
    cs:       CE0
    reset:    D0
  switch_A:
    ctrl1:    D1
    ctrl2:    D2
  switch_B:
    ctrl1:    D3
    ctrl2:    D4

# Special Packet Contents
send_pkt_num: false     # Whether we send the packet number
send_time:    false     # Whether we send the current time
call_sign:    AB0CDE    # Ham radio call sign (null = unlicensed)

# Packet Contents
packet_def:
  - 

# Supported data types:
# int8, int16, int32, int64, uint8, uint16, uint32, uint64,
# float32, float64, bool